package com.theokanning.openai.response.tool;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A call to a custom tool created by the model.
 *
 * @see <a href="https://platform.openai.com/docs/api-reference/response/create">Response API</a>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CustomToolCall extends ToolCall {

    /**
     * The type of the custom tool call. Always "custom_tool_call".
     */
    private String type = "custom_tool_call";

    /**
     * The unique ID of the custom tool call in the OpenAI platform.
     */
    private String id;

    /**
     * The name of the custom tool being called.
     */
    private String name;

    /**
     * An identifier used to map this custom tool call to a tool call output.
     */
    @JsonProperty("call_id")
    private String callId;

    /**
     * The input for the custom tool call generated by the model.
     */
    private String input;

    @Override
    public String getType() {
        return type;
    }
}
