package com.theokanning.openai.web;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Web Search Response based on Tavily Search API Contains search results, answer, images, and metadata from web search
 */
@Data
@SuperBuilder
@NoArgsConstructor
public class WebSearchResponse implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * The search query that was executed (required) Example: "Who is Leo Messi?"
     */
    private String query;

    /**
     * A short answer to the user's query, generated by an LLM (required) Included in the response only if include_answer is requested (i.e., set to
     * true, basic, or advanced) Example: "Lionel Messi, born in 1987, is an Argentine footballer widely regarded as one of the greatest players of
     * his generation..."
     */
    private String answer;

    /**
     * List of query-related images (required) If include_image_descriptions is true, each item will have url and description
     */
    private List<SearchImage> images;

    /**
     * A list of sorted search results, ranked by relevancy (required)
     */
    private List<SearchResult> results;

    /**
     * Time in seconds it took to complete the request (required) Example: 1.67
     */
    @JsonProperty("response_time")
    private Double responseTime;

    /**
     * A dictionary of the selected auto_parameters, only shown when auto_parameters is true Example: {"topic": "general", "search_depth": "basic"}
     */
    @JsonProperty("auto_parameters")
    private AutoParameters autoParameters;

    /**
     * A unique request identifier you can share with customer support to help resolve issues with specific requests Example:
     * "123e4567-e89b-12d3-a456-426614174111"
     */
    @JsonProperty("request_id")
    private String requestId;

    /**
     * Extra fields for future extensibility
     */
    @JsonIgnore
    private Map<String, Object> extraFields;

    /**
     * Flatten extra fields to the outer JSON during serialization
     */
    @JsonAnyGetter
    public Map<String, Object> getExtraFields() {
        return extraFields == null || extraFields.isEmpty() ? null : extraFields;
    }

    /**
     * Handle unknown properties during deserialization and store them in extraFields
     */
    @JsonAnySetter
    public void setExtraField(String key, Object value) {
        if(extraFields == null) {
            extraFields = new HashMap<>();
        }
        extraFields.put(key, value);
    }

    /**
     * Search Image class representing image search results
     */
    @Data
    @SuperBuilder
    @NoArgsConstructor
    public static class SearchImage implements Serializable {
        private static final long serialVersionUID = 1L;

        /**
         * The URL of the image
         */
        private String url;

        /**
         * Description of the image (only if include_image_descriptions is true)
         */
        private String description;
    }

    /**
     * Search Result class representing individual search results
     */
    @Data
    @SuperBuilder
    @NoArgsConstructor
    public static class SearchResult implements Serializable {
        private static final long serialVersionUID = 1L;

        /**
         * The title of the search result Example: "Lionel Messi Facts | Britannica"
         */
        private String title;

        /**
         * The URL of the search result Example: "https://www.britannica.com/facts/Lionel-Messi"
         */
        private String url;

        /**
         * A short description of the search result Example: "Lionel Messi, an Argentine footballer, is widely regarded..."
         */
        private String content;

        /**
         * The relevance score of the search result Example: 0.81025416
         */
        private Double score;

        /**
         * The cleaned and parsed HTML content of the search result Only if include_raw_content is true
         */
        @JsonProperty("raw_content")
        private String rawContent;

        /**
         * The favicon URL for the result Example: "https://britannica.com/favicon.png"
         */
        private String favicon;
    }

    /**
     * Auto Parameters class representing automatically selected parameters
     */
    @Data
    @SuperBuilder
    @NoArgsConstructor
    public static class AutoParameters implements Serializable {
        private static final long serialVersionUID = 1L;

        /**
         * Automatically selected topic
         */
        private String topic;

        /**
         * Automatically selected search depth
         */
        @JsonProperty("search_depth")
        private String searchDepth;

    }

}
