package com.theokanning.openai.response.tool.output;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.theokanning.openai.response.ConversationItem;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The output of a custom tool call from your code, being sent back to the model.
 *
 * @see <a href="https://platform.openai.com/docs/api-reference/response/create">Response API</a>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CustomToolCallOutput implements ConversationItem {

    /**
     * The type of the custom tool call output. Always "custom_tool_call_output".
     */
    private String type = "custom_tool_call_output";

    /**
     * The unique ID of the custom tool call output in the OpenAI platform.
     */
    private String id;

    /**
     * The call ID, used to map this custom tool call output to a custom tool call.
     */
    @JsonProperty("call_id")
    private String callId;

    /**
     * The output from the custom tool call generated by your code.
     */
    private String output;

    @Override
    public String getType() {
        return type;
    }
}
