package com.theokanning.openai.response.tool.output;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.theokanning.openai.response.ConversationItem;
import com.theokanning.openai.response.ItemStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The output of a function tool call.
 *
 * @see <a href="https://platform.openai.com/docs/api-reference/response/create">Response API</a>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class FunctionToolCallOutput implements ConversationItem {

    /**
     * The type of the function tool call output. Always "function_call_output".
     */
    @Builder.Default
    private String type = "function_call_output";

    /**
     * The unique ID of the function tool call output. Populated when this item is returned via API.
     */
    private String id;

    /**
     * The unique ID of the function tool call generated by the model.
     */
    @JsonProperty("call_id")
    private String callId;

    /**
     * A JSON string of the output of the function tool call.
     */
    private String output;

    /**
     * The status of the item.
     */
    private ItemStatus status;

    @Override
    public String getType() {
        return type;
    }
}
