package com.theokanning.openai.response.tool.output;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.theokanning.openai.response.ConversationItem;
import com.theokanning.openai.response.ItemStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The output of a local shell tool call.
 *
 * @see <a href="https://platform.openai.com/docs/api-reference/response/create">Response API</a>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class LocalShellCallOutput implements ConversationItem {

    /**
     * The type of the local shell tool call output. Always "local_shell_call_output".
     */
    private String type = "local_shell_call_output";

    /**
     * The unique ID of the local shell tool call generated by the model.
     */
    private String id;

    /**
     * A JSON string of the output of the local shell tool call.
     */
    private String output;

    /**
     * The status of the item.
     */
    private ItemStatus status;

    @Override
    public String getType() {
        return type;
    }
}
